نname: Build Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04  # استفاده از نسخه پایدارتر
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
        # نصب libtinfo5 از مخازن جایگزین اگر لازم بود
        sudo apt-get install -y libtinfo5 || sudo apt-get install -y libtinfo6

    - name: Build with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
      env:
        # تنظیم متغیر برای رفع خطای Aidl
        ANDROID_HOME: /usr/local/android-sdk
